### ISSUE TITLE
[Mermaid][Dark mode]  Derived colors are not re-calculated when switching modes

### ISSUE THREAD

**Issue by magic-debian** [zeon-studio/hugoplate#199]
### What is your Hugo Extended Version

hugo v0.147.5

### What is your Go Version

go1.24.3

### What is your Node.js Version

v22.16.0

### What is your Operating System

Debian GNU/Linux 12 (amd64)

### Check for Existing Issues

- [x] I have searched and found no relevant issues.

### Expected Behavior

Color re-calculation when switching from light mode to dark mode.
IE: black lines become white on dark mode
See example here: https://hugomods.com/docs/content/mermaid/

I tried adding the %%{init: {'theme':'forest'}}%% on top of my diagram without success, as suggested in the doc: http://mermaid.js.org/config/theming.html#theme-variables

Site wide definition was also a failure: http://mermaid.js.org/config/theming.html#site-wide-theme 

### Steps to Reproduce

Create a mermaid diagram
switch from light mode to dark mode

- The current "Elements" page of the demo has the same issue -

**Comment by tfsomrat** [comment]
Hey @magic-debian, we fixed the issue a long time ago. We are sorry for not letting you know at that moment. Thanks for your understanding. Have a good day

**Comment by BetaLyte** [comment]
I still see this issue on newest version of Hugoplate, and it's there on the demo page:

<img width="634" height="744" alt="Image" src="https://github.com/user-attachments/assets/9f996087-a9c3-4075-bf68-a0bbd6b44b05" />

**Comment by tfsomrat** [comment]
Hey @BetaLyte, the Update Script does not work well when it's a major version change since we released Hugoplate v3, which is based on a new templating system.  Please update the theme manually. thanks
